name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - type: "pre-exclude"
    when:
      labels:
        - "dependencies"
        - "skip-changelog"
  - title: "⚠️ Breaking changes"
    semver-increment: "major"
    when:
      label: "breaking-change"
  - title: "Features"
    semver-increment: "minor"
    when:
      label: "enhancement"
  - title: "Bug Fixes"
    when:
      label: "bug"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
