site_name: Meilisearch Python SDK
site_description: A Python async client for the Meilisearch API
site_url: https://meilisearch-python-sdk.paulsanders.dev

theme:
  name: material
  locale: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
repo_name: sanders41/meilisearch-python-sdk
repo_url: https://github.com/sanders41/meilisearch-python-sdk

nav:
  - Home: index.md
  - API:
      - AsyncClient: async_client_api.md
      - Client: client_api.md
      - AsyncIndex: async_index_api.md
      - Index: index_api.md
      - Decorators: decorators_api.md
  - Plugins: plugins.md
  - JSON Handler: json_handler.md
  - Pydantic: pydantic.md

plugins:
  - mkdocstrings
  - search

extra_javascript:
  - "js/umami.js"
