name: Docs Publish
on:
  release:
    types:
      - published
  workflow_dispatch:
env:
  PYTHON_VERSION: "3.13"
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.1
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: uv sync --frozen --all-extras
      - name: Configure Pages
        uses: actions/configure-pages@v6
      - name: Build Docs
        run: uv run zensical build --strict
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
